name: deploy-gh-pages

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v4

    - name: setup-conda
      uses: s-weigand/setup-conda@v1.2.4

    - run: conda install nbconvert -y

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.x.x

    - run: dotnet tool restore

    - name: Build
      working-directory: ./src
      run: dotnet fornax build

    - name: deploy
      uses: JamesIves/github-pages-deploy-action@v4.7.3
      with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: ./src/_public # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
